### ISSUE TITLE
Subdomains and ingress

### ISSUE THREAD

**Issue by Shaked** [allegroai/clearml-server-helm#3]
Hey, 

In order to connect between the services (app, files, api) and our nginx LB, we use an ingress that looks like this:

```
# Source: trains/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: release-name-trains
  labels:
    app.kubernetes.io/name: trains
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Tiller
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"

spec:
  tls:
    - hosts:
        - "app.trains-prod.example.com"
        - "files.trains-prod.example.com"
        - "api.trains-prod.example.com"
      secretName: tls-secret-prod.app.trains-prod-example.com
  rules:
    - host: "app.trains-prod.example.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: webserver-service
              servicePort: 80
    - host: "api.trains-prod.example.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: apiserver-service
              servicePort: 8008
    - host: "files.trains-prod.example.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: fileserver-service
              servicePort: 8081

```

This integrates with our certificate manager (letsencrypt) as well. 

I was thinking, would it make sense to add a PR that supports something like: 
```
helm install.... --set ingress.enabled=true --set ingress.annotations=THE_ANNOTATION --set ingress.app_host=app.trains-prod.example.com  --set ingress.files_host=files.trains-prod.example.com --set ingress.api_host=api.trains-prod.example.com 
```

Which will automatically support the above YAML? 

Thank you
Shaked

EDIT:

It seems like it's important to add `timeouts` otherwise nginx LB might return a 504 timeout sometimes:

![image](https://user-images.githubusercontent.com/960015/71815490-4d5f5400-3088-11ea-9664-08af1cb9478e.png)
